### ISSUE TITLE
Data not displayed for textarea in admin

### ISSUE THREAD

**Issue by risingisland** [GetSimpleCMS-CE-plugins/plugin-MultiField#2]
https://github.com/GetSimpleCMS-CE-plugins/plugin-MultiField/blob/f32d266db37a4cbcf521d6ae6c251294d1868ea7/multiField/view/extras.inc.php#L139

I think it is missing:

`:type="data['type']" :value="dater[data['label']]['value']"`

Not sure if needed:

`:x-bind:x-html="dater[data['label']]['value']"`

**Comment by multicolor-rgb** [comment]
fixed on 3.1.1
